sketch-hq/fig2sketch

README.md
converter/artboard.py
converter/tree.py
converter/utils.py
pyproject.toml
sketchformat/layer_group.py
tests/converter/test_artboard.py

Fixes #18
We cannot support everything, but we are better off with this. Some highlights:
- Sketch only supports grids/layout in artboards, so we ignore the rest.
- Single grids are well supported
- Sketch is limited to two grids and their sizes must be multiple of each other. In case the .fig grids is not compatible with this, we convert the smallest one and ignore the rest.
- Column layouts work ok. We have to do some work to convert the specification (recalculate the number of columns, etc) but work fine in most cases.
- Row layout support in Sketch is very limited, so in many cases we cannot convert it, or do so with poor fidelity:
- Sketch always uses the whole height of the artboard. If the .fig specifies a fixed height of layout, we ignore it
- Sketch imposes an integer ratio …

🏁 Support grids and layouts

---

converter/instance.py
tests/converter/test_instance.py

If a property and a symbol override are specified for the same symbol property, always take the component property, it always takes priority.

🧑🏻‍🤝‍🧑🏼 Solve conflicts between property and symbol override

---

.gitignore
converter/prototype.py
sketchformat/common.py
sketchformat/prototype.py
tests/converter/test_prototype.py

Adds support for overlays without a fixed position, but a manually picked one. In sketch this is translated by keeping a (0, 0) anchor position and setting the offset with the relative coordinates as found in the origin frame.

✋ Support manual position for overlays

---

converter/text.py
tests/converter/test_positioning.py
tests/converter/test_rectangle.py
tests/converter/test_style.py
tests/converter/test_text.py

This PR fixes 2 issues related to kerning:
- Set auto kerning (basically not including the property) when kerning is null or 0 in fig files
- Adjust text's frame width when text width is flexible and kerning is present (to avoid text cuts in Sketch)

↔ Fix kerning issues

---

README.md

As stated by [this tweet](https://twitter.com/cedriceberhardt/status/1597696006594105344), we actually require Python's version 3.10  since we use match which is just supported from that version forward.

🐍 Add accurate python version required in README

---

converter/artboard.py
converter/base.py
converter/document.py
converter/font.py
converter/group.py
converter/instance.py
converter/page.py
converter/positioning.py
converter/rectangle.py
converter/shape_path.py
converter/style.py
converter/symbol.py
converter/text.py
converter/tree.py
converter/utils.py
tests/converter/base.py
tests/converter/test_artboard.py
tests/converter/test_base.py
tests/converter/test_group.py

This PR adds basic support for sections which need to be handled the same way as frames in .fig files: if they hang directly under a canvas they're converted as artboards, and if they hang under another frame then they're converted as groups.
Fixes #60

§ Add support for sections

---

src/converter/base.py
src/converter/instance.py
src/converter/tree.py
src/figformat/fig2tree.py
tests/converter/test_base.py
tests/converter/test_instance.py
tests/converter/test_prototype.py
tests/converter/test_symbol.py

From bug reported in [this thread](https://sketch.slack.com/archives/C042X7DDDTK/p1670840731366069?thread_ts=1670839802.162329&cid=C042X7DDDTK)
This PRs prevents duplicated IDs that were being introduced for overrides in symbol instances.

⎶ Avoid duplicated IDs when handling overrides

---

src/converter/artboard.py
src/converter/group.py
src/converter/instance.py
src/converter/shape.py
src/converter/symbol.py
src/converter/text.py
tests/converter/base.py
tests/converter/test_symbol.py

If a symbol master was passed into `apply_inner_shadow`, it didn't match the `isinstance` if, so it tried to apply the shadow to the master itself. This modified itself while looping, which ended up adding infinite shadows to itself until it ran out of memory :boom: 
Fixes https://github.com/sketch-hq/Sketch/issues/48819

➿ Avoid infinite loop trying to apply innerShadow to a symbol master

---

src/converter/shape_path.py
src/converter/tree.py
src/converter/utils.py
tests/converter/test_shape_path.py

A shape path with no points used to produce an error. This converts it to a warning so it's less scary to the user.
https://github.com/sketch-hq/Sketch/issues/48908 Case 1

🪹 Skip empty shape paths

---

src/converter/errors.py
src/converter/instance.py
src/converter/tree.py
tests/converter/test_instance.py

Previous to this patch, when instances were detached they always converted to groups. It ignored the rule we have that converts some of them to artboards.
This was a problem in a document with a prototype where the screens were symbol instances. It converted all of them to groups so it broke all the transition information. By converting the detached instances to artboards when appropriate, the prototype works correctly.

🎬 Convert detached symbol instances to group/artboard as needed

---

src/figformat/fig2tree.py

When overrideKey is set to the invalid value, ignore it from the early stage. If not, the instance override code gets confused trying to apply the override for a key that cannot be found (UINT_MAX).

🔼 Ignore invalid override keys

---

src/figformat/kiwi.py

Changes between version 20 and 25:
```
--- schema20.txt	2023-04-17 10:53:43.271121864 +0200
+++ schema25.txt	2023-04-17 10:53:47.327788541 +0200
@@ -339,6 +339,11 @@
WRAP = 1;
}
+enum StackCounterAlignContent {
+  AUTO = 0;
+  SPACE_BETWEEN = 1;
+}
+
enum ConnectionType {
NONE = 0;
INTERNAL_NODE = 1;
@@ -1159,6 +1164,7 @@
LEFT = 3;
BOTTOM = 4;
RIGHT = 5;
+  CENTER = 6;
}
message ConnectorEndpoint {
@@ -1203,6 +1209,8 @@
message EditInfo {
string timestampIso8601 = 1;
+  string userId = 2;
+  uint lastEditedAt = 3;
}
enum EditorType {
@@ -1322,10 +1330,12 @@
string fontVersion = 202;
LeadingTrim leadingTrim = 322;
bool hangingQuote = 337;
+  bool hangingList = 339;
uint textUserLayoutVersion = 203;
OpenTypeFeature[] toggledOnOTFeatures = 205;
OpenTypeFeature[] toggledOffOTFeatures = 206; …
```

🔢 More flexible support of fig versions

---

README.md

Running these commands as is doesn't work in zsh (the default shell in macOS) since it treats square brackets as special characters:
```shell
pip install fig2sketch[fast]
```

README: make `pip install` invocations zsh-compatible

---

.github/workflows/release.yml

GitHub Actions supports M1 runners now. To avoid unexpected changes, x86_64 now uses macos-12 explicitly, arm64 uses macos-14 explicitly, following what the current default is for macos-latest.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories

ci: use github hosted arm runner

---

.github/workflows/release.yml

We were encountering a specific issue with Pyinstaller when trying to embed the universal binary in the Sketch bundle. We're mitigating this for now by moving to a specific Pyinstaller release

💥 Resolve pyinstaller release errors

---

src/converter/context.py
src/converter/convert.py
src/converter/document.py
tests/converter/test_base.py
tests/converter/test_image.py
tests/converter/test_instance.py
tests/converter/test_prototype.py
tests/converter/test_shape_path.py
tests/converter/test_symbol.py

Adds support for setting the output Sketch document's colour space to either sRGB or P3 based on the fig input

🎨 Add support for P3 color space

---

src/converter/context.py
src/converter/font.py

With https://github.com/sketch-hq/fig2sketch/pull/118 we patched google web font downloading to fix a breaking change on Google's end.
However, the font matching wasn't the most reliable, as we attempted to match against file names rather than the family and style names from the font file itself. I've refactored this to use the more reliable latter. However, the downside is downloading each font file for the family. The previous implementation did this but as a single ZIP file. Given fonts are typically very small, and ZIPing them appears to make a negligible difference, I've gone for a slight bandwidth increase for better reliability/conversion results.
Note: We will still see some errors downloading fonts regarding text styles with additional variant info in subfamily strings (such as …

🔨 Improve the reliability of web font matching

---

src/converter/base.py
src/converter/group.py
src/converter/shape_path.py
src/converter/style.py
src/converter/text.py
src/converter/tree.py

We've recently had instances of some frame and text layer properties not being written to the `.fig` model data. In these cases, we will fall back on the default values.
I have tackled the most common/those we've encountered but haven't provided defaults for everything at this time.

👀 Fallback to sensible defaults when reading some fig node properties

---

src/converter/style.py

Blend mode appears to be omitted from the `fig` model when it's set to `NORMAL`. This leads to a key error when processing a node. This small tweak uses `get` to ensure we fall back to `NORMAL` when the `blendMode` key isn't set.

👁️ Additional defaults for blend modes

---

src/converter/style.py

In some scenarios, `originalImageWidth` and `originalImageHeight` aren't present for image fills. In these cases, we fall back to the node dimensions.

📐 Fallback to node dimensions when original image dimensions aren't present

---

pyproject.toml
src/figformat/decodefig.py
src/figformat/kiwi.py

We have noticed that some parts of the `fig` file are now compressed using `zstd`. This leads to a crash when importing newly exported figma documents.
This change checks the first four bytes of the compressed range to look for the `zstd` "magic number" and switches decompression libraries based on the result.

🗜️ Support `zstd` compression algorithm

---

.github/workflows/adhoc_build.yml
.github/workflows/release.yml

The macOS 12 runner image will be removed by December 3rd, 2024.
This PR will update the existing runner to macOS13.

Update x86 runner to macOS13

---

src/converter/base.py
src/converter/context.py
src/converter/positioning.py
src/converter/prototype.py
src/converter/style.py
src/converter/utils.py

We have some issues where converting files may fail due to:
1. Division by zero - I've made an effort to cover most of these with a safe division function
2. Missing node - We now throw a specific fig2sketch warning so that its clearer/can be better handled in the future.

Better handling of missing nodes and division by zero

---

.github/workflows/adhoc_build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

I've tested the main build workflow [here](https://github.com/sketch-hq/fig2sketch/actions/runs/14169557298). However, note that the warnings are coming from the `actions-rs/toolchain@v1` action, which has been archived here on Github. We will need to seek a replacement for this.

🤖 Update `checkout` and `setup-python` github action versions

---

.github/workflows/adhoc_build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

The previous action's ([`actions-rs/toolchain@v1`](https://github.com/actions-rs/toolchain)) repo has now been archived and is no longer maintained, and it's using soon to be deprecated workflow features (`set-output`).
So I've migrated this project's workflows to [`actions-rust-lang/setup-rust-toolchain@v1`](https://github.com/actions-rust-lang/setup-rust-toolchain)

⚙️ Replace Rust toolchain setup Github action

---

src/converter/base.py
src/converter/frame.py
src/converter/group.py
src/converter/layout.py
src/converter/page.py
src/converter/positioning.py
src/converter/rectangle.py
src/converter/style.py
src/converter/symbol.py
src/converter/tree.py
src/converter/utils.py
src/sketchformat/layer_common.py
src/sketchformat/layer_group.py
src/sketchformat/style.py
tests/converter/test_group.py
tests/converter/test_layout.py
tests/converter/test_style.py
tests/converter/test_symbol.py

Adds support for converting Figma auto layout to Sketch Stack Layouts (introduced in Sketch `2025.1`)

🥞  Implement stacks

---

src/converter/group.py
src/converter/shape_path.py
src/converter/style.py
src/converter/symbol.py
src/converter/utils.py
tests/converter/test_symbol.py

- **Introduce new error to handle vectors with no regions**
- **No need to clip symbols now that frames support corner radius in Sketch**

🐞 Remove clipping masks from symbols and skip vectors missing regions

---

src/figformat/fig2tree.py

Simple polygons (squares and rectangles) may no longer come with an explicit vector network defined, as the path can be inferred from the node's frame. `fig2sketch` is crashing when it encounters a `vectorData` map without a `vectorNetworkBlob` field.
Sketch will still render these nodes correctly without providing a vector network, and so we'll skip decoding them if `vectorNetworkBlob` isn't set.

🏃 Skip decoding `vectorNetwork` when nodes are missing `vectorNetworkBlob`

---

src/converter/base.py

Based on testing and bug reports it appears that Figma's default mask mode is \`ALPHA\` and when set, its omitted from the figma model. This means we need to tweak our \`get\` default to match

Change the default value when reading `maskType` for `clippingMaskMode`

---

src/converter/style.py
src/sketchformat/style.py
tests/converter/test_style.py

Both Figma and Sketch now support "progressive blurs". We need to convert from Figma's simple progressive blur model to Sketch's gradient-backed progressive blur model.

Add support for progressive layer blurs
